### ISSUE TITLE
Not supported empty or null <includes> and <excludes>

### ISSUE THREAD

**Issue by JuanMiguelBG** [codehaus-plexus/plexus-utils#10]
Not supported empty or null <includes> and <excludes>. The problems are on the methods _setExcludes( String[] excludes )_  and _setIncludes( String[] includes )_ of the class _org.codehaus.plexus.util.AbstractScanner_.

They throws _NullPointerException_ when call the method _normalizePattern( String pattern )_.

**Comment by ChristianSchulte** [comment]
Issue got fixed in commit [2644af5a8a51bbaf2cc307386b81d63069954e46](https://github.com/codehaus-plexus/plexus-utils/commit/2644af5a8a51bbaf2cc307386b81d63069954e46).
