### ISSUE TITLE
Inactive unit tests hide endless loop in MXParser

### ISSUE THREAD

**Issue by joehni** [codehaus-plexus/plexus-utils#118]
A bunch of unit tests of org.codehaus.plexus.util.xml.pull.MXParserTest are inactive, because they lack the@Test annotation. However, if you activate them, some will result in an endless loop (DoS attack !). The problem had actually been solved once by Gabrial Belingues (in 7e54bff868584cd3bfd7be59b9499e762f0d70ac), but was introduced again by Todd Lipcon (in 59cf121cba636d76b7788d63667b1a112845d767) and overseen because the tests did not execute. The change also re-introduced #80.

**Comment by michael-o** [comment]
Interesting...

**Comment by belingueres** [comment]
Good catch! I'll send a quick fix in these days.

**Comment by joehni** [comment]
The handling of the XML in the processing instruction unfortunately still opens a hole for the DoS attack with an endless loop:

```Java
    @Test
    public void testMalformedProcessingInstructionsContainingXmlNoClosingQuestionMark()
        throws Exception
    {
        StringBuffer sb = new StringBuffer();
        sb.append( "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" );
        sb.append( "<project />" );
        sb.append( "<?pi\n" );
        sb.append( "   <tag>\n" );
        sb.append( "   </tag>>\n" );

        Xpp3Parser parser = new Xpp3Parser();
        parser.setInput( new StringReader( sb.toString() ) );

        try
        {
            assertEquals( XmlPullParser.PROCESSING_INSTRUCTION, parser.nextToken() );
            assertEquals( XmlPullParser.START_TAG, parser.nextToken() );
            assertEquals( XmlPullParser.END_TAG, parser.nextToken() );
            assertEquals( XmlPullParser.PROCESSING_INSTRUCTION, parser.nextToken() );
            
            fail( "Should fail since it has invalid PI" );
        }
        catch ( XmlPullParserException ex )
        {
            assertTrue( ex.getMessage().contains( "processing instruction started on line 3 and column 2 was not closed" ) );
        }
    }
```

**Comment by belingueres** [comment]
Seems there are still several (unrelated?) issues to fix. Could you open new, independent issues explaining the problems you just found and their expected behavior?

**Comment by belingueres** [comment]
Hi @joehni !
I've created a project to test the MXParser against the XML conformance test suite. I think it is a good starting point for parser improvement for the future: https://github.com/belingueres/xml-conformance
