### ISSUE TITLE
MXParser fails to recognize illegal character references

### ISSUE THREAD

**Issue by belingueres** [codehaus-plexus/plexus-utils#132]
Discovered with the help of https://github.com/belingueres/xml-conformance

MXParser fails on parts of the W3C XML Conformance Test Suite.

In this issue, it is failing ibm66n01.xml, ibm66n03.xml, ibm66n05.xml, ibm66n07.xml, ibm66n09.xml, ibm66n11.xml  from "IBM XML Conformance Test Suite - Production 66" (see https://github.com/belingueres/xml-conformance/blob/main/src/test/resources/xmlconf/ibm/ibm_oasis_not-wf.xml) regarding the parsing of invalid character references.

**Comment by cstamas** [comment]
Most probably causes https://github.com/codehaus-plexus/plexus-utils/issues/238
