### ISSUE TITLE
MXParser failing to parse properly 'encoding' declaration attribute

### ISSUE THREAD

**Issue by belingueres** [codehaus-plexus/plexus-utils#134]
Discovered with the help of https://github.com/belingueres/xml-conformance

MXParser fails on parts of the W3C XML Conformance Test Suite.

In this issue, it is failing ibm80n01.xml from "IBM XML Conformance Test Suite - Production 80" (see https://github.com/belingueres/xml-conformance/blob/main/src/test/resources/xmlconf/ibm/ibm_oasis_not-wf.xml) regarding the encoding in the declaration section of the xml file.

**Comment by michael-o** [comment]
Fixed with a16c27b703b35166f167e116cf7c0a3a12fa975e.
