### ISSUE TITLE
MXParser improve error reporting when parsing large char entities and invalid encoding declarations

### ISSUE THREAD

**Issue by belingueres** [codehaus-plexus/plexus-utils#136]
Discovered with the help of https://github.com/belingueres/xml-conformance

MXParser fails on parts of the W3C XML Conformance Test Suite.

In this issue, it is failing 001.xml to 004.xml, and 007.xml to 009.xml from "Bjoern Hoehrmann via HST 2013-09-18" (see https://github.com/belingueres/xml-conformance/blob/main/src/test/resources/xmlconf/eduni/misc/ht-bh.xml) regarding the parsing of large character entities and encoding in the declaration section of the xml file.
Tests 005.xml and 006.xml were ignored as MXParser do not support DOCDECL parsing.

**Comment by michael-o** [comment]
Fixed with 1e18ddcc98f318b36449102f3267fd4631cc668b.
