### ISSUE TITLE
BourneShell results in error when /bin/sh is symlink'd to bash

### ISSUE THREAD

**Issue by ctubbsii** [codehaus-plexus/plexus-utils#14]
When /bin/sh is symlink'd to bash (which it frequently is), the execution of the command results in an error:

```
/bin/sh: scl: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `BASH_FUNC_scl'
```

This is due to a missing semicolon in the command line. This is required by bash when executing a function as a one-liner. See http://tldp.org/LDP/abs/html/functions.html

(See related mojohaus/maven-native/issues/3)

**Comment by michael-o** [comment]
How to fix this?

**Comment by ctubbsii** [comment]
The fix is for the plugin to terminate the constructed command line with a semicolon before the closing brace.

**Comment by michael-o** [comment]
This has to be fixed in plexus-utils? (sorry for being stupid)

**Comment by ctubbsii** [comment]
I'm pretty sure that plexus-utils provides the relevant code for constructing a command line instruction. It's been awhile since I investigated this.

**Comment by ctubbsii** [comment]
Okay, so, I misunderstood the problem. The problem is with the injected system environment variables. In older versions of plexus-utils (prior to 2.0.2), the `CommandLineUtils.getSystemEnvVars(boolean)` method actually executed `env` and processed its STDOUT in order to gather environment variables. There was a bug in that processing which didn't handle newlines or quoting (or something, not sure) correctly in environment variables.

Starting in version 2.0.2 (from the code comments), it used `System.getenv()`, instead of doing its own thing to get the environment for the child process.

The specific environment variable causing the problem I saw was this one:
```bash
BASH_FUNC_scl()=() {  local CMD=$1;
 if [ "$CMD" = "load" -o "$CMD" = "unload" ]; then
 eval "module $@";
 else
 /usr/bin/scl "$@";
 fi
}
```
In the older version of plexus-utils (`<=2.0.1`), this got truncated to one line:
```bash
BASH_FUNC_scl()=() {  local CMD=$1;
```

And there were several other discrepancies with the environment from what should have been there, too.

This is fixed in newer versions. I will close this issue. Sorry for the confusion.
