### ISSUE TITLE
Is IOEx necessary

### ISSUE THREAD

**Issue by cstamas** [codehaus-plexus/plexus-utils#206]
Env variable related methods like these:
https://github.com/codehaus-plexus/plexus-utils/blob/master/src/main/java/org/codehaus/plexus/util/cli/CommandLineUtils.java#L361
https://github.com/codehaus-plexus/plexus-utils/blob/master/src/main/java/org/codehaus/plexus/util/cli/CommandLineUtils.java#L377

Is `throws IOException` necessary? If so, why?

**Comment by michael-o** [comment]
I think relic. I my opinion, we can throw it away.
