### ISSUE TITLE
StringUtils.isNotEmpty() does not negate StringUtils.isEmpty()

### ISSUE THREAD

**Issue by kwin** [codehaus-plexus/plexus-utils#214]
While the latter does a `trim()` (https://github.com/codehaus-plexus/plexus-utils/blob/8a9147a07332b9ef554c9aa695aa4105532167e2/src/main/java/org/codehaus/plexus/util/StringUtils.java#L184-L187) and is actually doing `StringUtils.isBlank()` the former does never trim.

See also the note added in plexus-utils 1.5.2 (released in 2008): https://github.com/codehaus-plexus/plexus-utils/commit/800c53c0be4eca73c6e4f76eed590c1e436597ec

**Comment by michael-o** [comment]
I'd push a 3.5.0 with this fixed finally after 14 years.
