### ISSUE TITLE
Xpp3DomUtils#mergeIntoXpp3Dom() must not override the dominant value in case it is empty

### ISSUE THREAD

**Issue by kwin** [codehaus-plexus/plexus-utils#216]
Although that behaviour is also stated in its [javadoc](https://github.com/codehaus-plexus/plexus-utils/blob/8a9147a07332b9ef554c9aa695aa4105532167e2/src/main/java/org/codehaus/plexus/util/xml/Xpp3DomUtils.java#L98) it is highly unexpected.  Rather a dominant empty value element should take precedence over the same named recessive element value. This would be necessary for https://issues.apache.org/jira/browse/MNG-6434 to work as expected.

**Comment by michael-o** [comment]
...an empty string is still a valid string...unless you use Oracle :-)
