### ISSUE TITLE
Strict XML parser breaks Maven backward compatibility

### ISSUE THREAD

**Issue by cstamas** [codehaus-plexus/plexus-utils#238]
This change:
https://github.com/codehaus-plexus/plexus-utils/commit/761ac423ce668d0681e30b4c2b75cb44a99234a9

The p-u XML parser is made stricter, and adhere standard, which is fine, but there is a problem: older Maven versions were able to parse, hence build and deploy projects that used POMs that does not adhere to strict(er) XML parsing. If it happens for user to pick up such POM (ie. among transitive dependencies), there is no breakout for user from that situation.

Also, see issue https://issues.apache.org/jira/browse/MNG-7697

Proposal: add some "lax-standards" switch for this. I agree that project POMs should fully adhere to XML 1.0 (so MNG-7697 is IMHO a fluke), but dependency POMs should be parsed with "laxed" standards, just like dependency POMs validation is laxed as well, given they are probably built and deployed with Maven versions pre-3.9.0, and MAY contain invalid characters as those versions would allow emojis in comments...

ping @belingueres

**Comment by michael-o** [comment]
I imagine a system property for this...

**Comment by cstamas** [comment]
Why a system property? Am fine to keep strict XML 1.0 parsing for project POM, but lax parsing for dependency POMs... how would a system property help here?

**Comment by michael-o** [comment]
> Why a system property? Am fine to keep strict XML 1.0 parsing for project POM, but lax parsing for dependency POMs... how would a system property help here?

Hoe is Plexus supposed to make the difference?

**Comment by slawekjaranowski** [comment]
can be couse of https://github.com/mojohaus/build-helper-maven-plugin/issues/168

**Comment by belingueres** [comment]
Hi:
Sorry for the late reply.
@cstamas : I confirm that change is detecting the emoji as an invalid character.
@slawekjaranowski: the [https://github.com/mojohaus/build-helper-maven-plugin/issues/168](https://github.com/mojohaus/build-helper-maven-plugin/issues/168) I confirm this is a bug. I'll be working on this issue first.

**Comment by gnodet** [comment]
> Hi:
> Sorry for the late reply.
> @cstamas : I confirm that change is detecting the emoji as an invalid character.

Fixed with #240 

> @slawekjaranowski: the [mojohaus/build-helper-maven-plugin#168](https://github.com/mojohaus/build-helper-maven-plugin/issues/168) I confirm this is a bug. I'll be working on this issue first.

Fixed with https://github.com/takari/polyglot-maven/pull/259 / https://github.com/eclipse-tycho/tycho/pull/2176 . I don't think this is an issue for the mx parser.
