### ISSUE TITLE
UT improvement : Check that symlinks resources are preserved during git clone

### ISSUE THREAD

**Issue by axel3rd** [codehaus-plexus/plexus-utils#24]
Following #20, some tests fail when [symlinks resources](https://github.com/codehaus-plexus/plexus-utils/tree/master/src/test/resources/symlinks/src) are not preserved during `git clone` :

``` 
DirectoryScannerTest.testFollowSymlinks:186 null
DirectoryScannerTest.testFollowSymlinksFalse:155 expected:<9> but was:<11>
```

In this case, the [core.symlinks](https://github.com/git-for-windows/git/wiki/Symbolic-Links) option should be used:
```
git clone -c core.symlinks=true https://github.com/codehaus-plexus/plexus-utils.git
```

**Comment by axel3rd** [comment]
*NB*: These 2 unit test fail on Windows too, so #20 PR was so bad ...

**Comment by belingueres** [comment]
You need to run the command as Admin too.
IMO a comment in the README.md should be enough. WDYT?

**Comment by axel3rd** [comment]
> IMO a comment in the README.md should be enough. WDYT?

`core.symlinks=true` + *admin mode* are required. `README` is a way, but this is the goal of #25 with [message](https://github.com/codehaus-plexus/plexus-utils/pull/25/files#diff-6a5e1d915294906ec31d9a38755c3e2fR149) and [UT skip](https://github.com/codehaus-plexus/plexus-utils/pull/25/files#diff-6a5e1d915294906ec31d9a38755c3e2fR190).

**Comment by belingueres** [comment]
It turned out that I'd been working on a similar issue some time ago. See [MSHARED-574](https://issues.apache.org/jira/browse/MSHARED-574). Please check if the applied solution for that issue fits your current needs.

**Comment by axel3rd** [comment]
> Please check if the applied solution for that issue fits your current needs.

This solution seems *fail* the unit test on Windows 10 (if *admin mode* & git option not set) ; The PR discussions ([maven-shared#16](https://github.com/apache/maven-shared/pull/16) & [plexus-utils#25](https://github.com/codehaus-plexus/plexus-utils/pull/25))  say that a better approach is not execute this unit tests (but no fail).
