### ISSUE TITLE
MXParser error when parsing an UTF-8 file without BOM and ISO-8859-1 element encoding

### ISSUE THREAD

**Issue by belingueres** [codehaus-plexus/plexus-utils#242]
Taken as a source this issue: https://github.com/mojohaus/build-helper-maven-plugin/issues/168 a new regression has been found, when trying to parse a file encoded as UTF-8 with no BOM, and the element encoding is ISO-8859-1, throwing and exception with this message:

"UTF-8 BOM plus xml decl of ISO-8859-1 is incompatible ..."

**Comment by elharo** [comment]
What should happen:

1. Fix the error message.
2. Deprecate the methods that read from a reader. Read from an input stream instead.
