### ISSUE TITLE
Possible hang in XML Parser

### ISSUE THREAD

**Issue by rohanpadhye** [codehaus-plexus/plexus-utils#35]
Found another XML issue via Maven, but not sure if it is rooted in plexus-utils.

hang.xml:
```
<project /><?>
```
Test:
```
mvn -f hang.xml
> [INFO] Scanning for projects...   # Gets stuck here forever
```

My profiler shows me that 100% CPU is being spent in: `org.codehaus.plexus.util.xml.XmlReader.read()`.

I've reported this to Maven in [MGN-6374](https://issues.apache.org/jira/browse/MNG-6374), but I'm not sure which is the right project to report this to.

Versions affected: Maven 3.5.2 and plexus-utils 3.1.0.

This issue was also encountered when fuzzing with [JQF](https://github.com/rohanpadhye/jqf).

**Comment by michael-o** [comment]
That's fine, this is the upstream issue, MNG is the downstream one.
