### ISSUE TITLE
doCopyFileUsingNewIO does not follow symlinks

### ISSUE THREAD

**Issue by msimacek** [codehaus-plexus/plexus-utils#45]
`doCopyFileUsingNewIO` does not follow symlinks which is inconsistent with `doCopyFileUsingLegacyIO`.

**Comment by ebourg** [comment]
This causes the maven-dependency-plugin to fail in Debian, because relative symlink are copied instead of the actual targeted file. Once copied the symlink is invalid and points to nothing.

**Comment by michael-o** [comment]
Friends, ping me in a week or so if I haven't merge this yet. Can someone provide a link to the old solution? This looks straight forward to me.

**Comment by mizdebsk** [comment]
This problem still affects plexus-utils 3.2.0.
@michael-o What do you mean by "the old solution"?
