### ISSUE TITLE
Missing release tags

### ISSUE THREAD

**Issue by ebourg** [codehaus-plexus/plexus-utils#5]
Hi,

The codehaus-plexus/plexus-utils repository is missing tags which were present in the sonatype/plexus-utils repository. Here are the commands to add them back:

    git tag 3.0.21 859590100d6177108424ed120e1bb8ca86ff0b54
    git tag 3.0.20 dc6ed699c644d649622f85bdf85d0684e54c11f6
    git tag 3.0.19 08e46b90d2b8ebd7adfcdb5cc9cfb3df37c43cd0
    git tag 3.0.18 a4ef5af0a58e4b0f1d08db4fc25a793139a1ad21
    git tag 3.0.17 3dd5750645d806aeeae174e5268609d927660e0b
    git tag 3.0.16 cf317f9b4070c3c619e9ee75a3e38bea3ff621c1
    git tag 3.0.15 3b271b43f9e5021b4232fc2ffdfb4e469c7f8685
    git tag 3.0.14 e434f28f0a2f9175a493be39c47176aeb3d00469
    git tag 3.0.13 5d446205de12702bf1734e2893a919bf599c3c12
    git tag 3.0.12 b60b2d5f5dc534ec7f9ef23ea31cef42d0dda2ea
    git tag 3.0.11 9f1b1dffcfe474c574b2b3041201f5c6692d8b7f
    git tag 3.0.10 a09697db5ee87f97180b1c84b5bbdef47ba28658
    git tag 3.0.9 64c77268243d963a560ac80939e47182b8c11529
    git tag 3.0.8 b0c708017f813ec9b7799fe82b4bc4bfd1631c53
    git tag 3.0.7 23cb9cba9d7ba020547802a45b2991dee99dbcb1
    git tag 3.0.6 4332f7bd3c51ff3496998fdcb2d00a38e067630d
    git tag 3.0.5 b50fe89cfb368e06dabc340b851504a2a2f25c47
    git tag 3.0.4 76880d4187130c8142b887c55d05c1cb349e2dc2
    git tag 3.0.3 c07eb85ab8a59dd73d00449f33e3bc57924123e2
    git tag 3.0.2 2b5a6c3645602fd19932d6a6bce07e9c9bf9b29f
    git tag 3.0.1 f1ee873df4113eae791face1984e14e2b37440ad
    git tag 3.0 b0e8713ff665f7fb5c8fcf6ae40d1ee03147db97
    git tag 2.1 01d252ac6be7f132d37a632b9ddbdd345b037181
    git push --tags

**Comment by hboutemy** [comment]
appplied, thank you
notice I named the tags "plexus-utils-*" to match existing tags, and 3.0.9 is not at this commit

**Comment by ebourg** [comment]
Merci !
