### ISSUE TITLE
apidoc is not generated for plexus-utils

### ISSUE THREAD

**Issue by ebarboni** [codehaus-plexus/plexus-utils#6]
Hi,
 the plexus-utils is missing did not generate apidoc the web page: http://codehaus-plexus.github.io/plexus-utils/ offer the javadoc link but lead to 404.

I detect the issue from this page https://maven.apache.org/doxia/doxia-sitetools/doxia-site-renderer/

**Comment by michael-o** [comment]
Guys, can you kindly generate and upload Javadocs?

**Comment by hboutemy** [comment]
I just did it

**Comment by agabrys** [comment]
hi, the problem occurs again.
