### ISSUE TITLE
Updating incompatible issue

### ISSUE THREAD

**Issue by SElab2019** [codehaus-plexus/plexus-utils#69]
Hi,

When I try to update plexus-utils to the version after 3.0.23. I got an incompatible issue. The change of API PropertyUtils.loadProperties breaks rolling upgrades.

Thanks a lot.

**Comment by michael-o** [comment]
So? What do you expect now?

**Comment by SElab2019** [comment]
> So? What do you expect now?

The following code breaks due to the change of loadProperties.

```
public static void inject(final MavenProject project, final InputStream properties) throws MojoFailureException {
    final Properties defaults = PropertyUtils.loadProperties(properties);
    final NarProperties nar = getInstance(project);
    nar.properties.putAll(defaults);
}
```

It should pass. But it throws an error now:
`
unreported exception java.io.IOException; must be caught or declared to be thrown
`
