### ISSUE TITLE
Remove .gitignore from DEFAULT_EXCLUDES

### ISSUE THREAD

**Issue by kwin** [codehaus-plexus/plexus-utils#71]
The .gitignore file is supposed to be committed to the git repository and is therefore a regular file. Still it is excluded by default. IMHO this filename should not be listed in DEFAULT_EXCLUDES: https://github.com/codehaus-plexus/plexus-utils/blob/5e238665d008f99db4766ffba882d306b20d0fe0/src/main/java/org/codehaus/plexus/util/AbstractScanner.java#L55

Compare also with https://issues.apache.org/jira/browse/SCM-883.

**Comment by michael-o** [comment]
The same applies for `"**/.gitattributes",` `"**/.hgignore"`.
