### ISSUE TITLE
Support combine.self="remove"

### ISSUE THREAD

**Issue by mwisnicki** [codehaus-plexus/plexus-utils#74]
Ability to remove inherited nodes would be super useful for maven:  https://issues.apache.org/jira/browse/MNG-6808

Spec: 
https://oss.sonatype.org/service/local/repositories/releases/archive/org/atteo/xml-combiner/2.2/xml-combiner-2.2-javadoc.jar/!/org/atteo/xmlcombiner/CombineSelf.html#REMOVE

**Comment by rfscholte** [comment]
Fixed with #75
